package cn.hiczy.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 m_id = 1;</code>
     * @return The mId.
     */
    long getMId();

    /**
     * <pre>
     *消息类
     * </pre>
     *
     * <code>.Message.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类
     * </pre>
     *
     * <code>.Message.MessageType type = 2;</code>
     * @return The type.
     */
    Message.MessageType getType();

    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     * @return Whether the authRsp field is set.
     */
    boolean hasAuthRsp();
    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     * @return The authRsp.
     */
    AuthResponseProto.AuthResponse getAuthRsp();
    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     */
    AuthResponseProto.AuthResponseOrBuilder getAuthRspOrBuilder();

    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     * @return Whether the plainMessage field is set.
     */
    boolean hasPlainMessage();
    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     * @return The plainMessage.
     */
    PlainMessageProto.PlainMessage getPlainMessage();
    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     */
    PlainMessageProto.PlainMessageOrBuilder getPlainMessageOrBuilder();

    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     * @return Whether the normalResponse field is set.
     */
    boolean hasNormalResponse();
    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     * @return The normalResponse.
     */
    NormalResponseProto.NormalResponse getNormalResponse();
    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     */
    NormalResponseProto.NormalResponseOrBuilder getNormalResponseOrBuilder();

    /**
     * <pre>
     *会话id
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The sessionId.
     */
    String getSessionId();
    /**
     * <pre>
     *会话id
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <pre>
     *jwt
     * </pre>
     *
     * <code>string jwt = 7;</code>
     * @return The jwt.
     */
    String getJwt();
    /**
     * <pre>
     *jwt
     * </pre>
     *
     * <code>string jwt = 7;</code>
     * @return The bytes for jwt.
     */
    com.google.protobuf.ByteString
        getJwtBytes();

    public Message.OnlyFiledCase getOnlyFiledCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 0;
      sessionId_ = "";
      jwt_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              mId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              AuthResponseProto.AuthResponse.Builder subBuilder = null;
              if (onlyFiledCase_ == 3) {
                subBuilder = ((AuthResponseProto.AuthResponse) onlyFiled_).toBuilder();
              }
              onlyFiled_ =
                  input.readMessage(AuthResponseProto.AuthResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((AuthResponseProto.AuthResponse) onlyFiled_);
                onlyFiled_ = subBuilder.buildPartial();
              }
              onlyFiledCase_ = 3;
              break;
            }
            case 34: {
              PlainMessageProto.PlainMessage.Builder subBuilder = null;
              if (onlyFiledCase_ == 4) {
                subBuilder = ((PlainMessageProto.PlainMessage) onlyFiled_).toBuilder();
              }
              onlyFiled_ =
                  input.readMessage(PlainMessageProto.PlainMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((PlainMessageProto.PlainMessage) onlyFiled_);
                onlyFiled_ = subBuilder.buildPartial();
              }
              onlyFiledCase_ = 4;
              break;
            }
            case 42: {
              NormalResponseProto.NormalResponse.Builder subBuilder = null;
              if (onlyFiledCase_ == 5) {
                subBuilder = ((NormalResponseProto.NormalResponse) onlyFiled_).toBuilder();
              }
              onlyFiled_ =
                  input.readMessage(NormalResponseProto.NormalResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((NormalResponseProto.NormalResponse) onlyFiled_);
                onlyFiled_ = subBuilder.buildPartial();
              }
              onlyFiledCase_ = 5;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              jwt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_Message_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * Protobuf enum {@code Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>PLAIN = 0;</code>
       */
      PLAIN(0),
      /**
       * <pre>
       *认证请求
       * </pre>
       *
       * <code>AUTH_REQ = 1;</code>
       */
      AUTH_REQ(1),
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>AUTH_RSP = 2;</code>
       */
      AUTH_RSP(2),
      /**
       * <pre>
       *心跳检测请求
       * </pre>
       *
       * <code>HEARTBEAT_REQ = 3;</code>
       */
      HEARTBEAT_REQ(3),
      /**
       * <pre>
       *心跳检测响应
       * </pre>
       *
       * <code>HEARTBEAT_RSP = 4;</code>
       */
      HEARTBEAT_RSP(4),
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>NORMAL_RSP = 5;</code>
       */
      NORMAL_RSP(5),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>PLAIN = 0;</code>
       */
      public static final int PLAIN_VALUE = 0;
      /**
       * <pre>
       *认证请求
       * </pre>
       *
       * <code>AUTH_REQ = 1;</code>
       */
      public static final int AUTH_REQ_VALUE = 1;
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>AUTH_RSP = 2;</code>
       */
      public static final int AUTH_RSP_VALUE = 2;
      /**
       * <pre>
       *心跳检测请求
       * </pre>
       *
       * <code>HEARTBEAT_REQ = 3;</code>
       */
      public static final int HEARTBEAT_REQ_VALUE = 3;
      /**
       * <pre>
       *心跳检测响应
       * </pre>
       *
       * <code>HEARTBEAT_RSP = 4;</code>
       */
      public static final int HEARTBEAT_RSP_VALUE = 4;
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>NORMAL_RSP = 5;</code>
       */
      public static final int NORMAL_RSP_VALUE = 5;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return PLAIN;
          case 1: return AUTH_REQ;
          case 2: return AUTH_RSP;
          case 3: return HEARTBEAT_REQ;
          case 4: return HEARTBEAT_RSP;
          case 5: return NORMAL_RSP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.MessageType)
    }

    private int onlyFiledCase_ = 0;
    private Object onlyFiled_;
    public enum OnlyFiledCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      AUTH_RSP(3),
      PLAIN_MESSAGE(4),
      NORMAL_RESPONSE(5),
      ONLYFILED_NOT_SET(0);
      private final int value;
      private OnlyFiledCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static OnlyFiledCase valueOf(int value) {
        return forNumber(value);
      }

      public static OnlyFiledCase forNumber(int value) {
        switch (value) {
          case 3: return AUTH_RSP;
          case 4: return PLAIN_MESSAGE;
          case 5: return NORMAL_RESPONSE;
          case 0: return ONLYFILED_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public OnlyFiledCase
    getOnlyFiledCase() {
      return OnlyFiledCase.forNumber(
          onlyFiledCase_);
    }

    public static final int M_ID_FIELD_NUMBER = 1;
    private long mId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int64 m_id = 1;</code>
     * @return The mId.
     */
    @Override
    public long getMId() {
      return mId_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *消息类
     * </pre>
     *
     * <code>.Message.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类
     * </pre>
     *
     * <code>.Message.MessageType type = 2;</code>
     * @return The type.
     */
    @Override public MessageType getType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(type_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int AUTH_RSP_FIELD_NUMBER = 3;
    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     * @return Whether the authRsp field is set.
     */
    @Override
    public boolean hasAuthRsp() {
      return onlyFiledCase_ == 3;
    }
    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     * @return The authRsp.
     */
    @Override
    public AuthResponseProto.AuthResponse getAuthRsp() {
      if (onlyFiledCase_ == 3) {
         return (AuthResponseProto.AuthResponse) onlyFiled_;
      }
      return AuthResponseProto.AuthResponse.getDefaultInstance();
    }
    /**
     * <pre>
     *认证响应
     * </pre>
     *
     * <code>.AuthResponse auth_rsp = 3;</code>
     */
    @Override
    public AuthResponseProto.AuthResponseOrBuilder getAuthRspOrBuilder() {
      if (onlyFiledCase_ == 3) {
         return (AuthResponseProto.AuthResponse) onlyFiled_;
      }
      return AuthResponseProto.AuthResponse.getDefaultInstance();
    }

    public static final int PLAIN_MESSAGE_FIELD_NUMBER = 4;
    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     * @return Whether the plainMessage field is set.
     */
    @Override
    public boolean hasPlainMessage() {
      return onlyFiledCase_ == 4;
    }
    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     * @return The plainMessage.
     */
    @Override
    public PlainMessageProto.PlainMessage getPlainMessage() {
      if (onlyFiledCase_ == 4) {
         return (PlainMessageProto.PlainMessage) onlyFiled_;
      }
      return PlainMessageProto.PlainMessage.getDefaultInstance();
    }
    /**
     * <pre>
     *普通消息
     * </pre>
     *
     * <code>.PlainMessage plain_message = 4;</code>
     */
    @Override
    public PlainMessageProto.PlainMessageOrBuilder getPlainMessageOrBuilder() {
      if (onlyFiledCase_ == 4) {
         return (PlainMessageProto.PlainMessage) onlyFiled_;
      }
      return PlainMessageProto.PlainMessage.getDefaultInstance();
    }

    public static final int NORMAL_RESPONSE_FIELD_NUMBER = 5;
    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     * @return Whether the normalResponse field is set.
     */
    @Override
    public boolean hasNormalResponse() {
      return onlyFiledCase_ == 5;
    }
    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     * @return The normalResponse.
     */
    @Override
    public NormalResponseProto.NormalResponse getNormalResponse() {
      if (onlyFiledCase_ == 5) {
         return (NormalResponseProto.NormalResponse) onlyFiled_;
      }
      return NormalResponseProto.NormalResponse.getDefaultInstance();
    }
    /**
     * <pre>
     *普通响应
     * </pre>
     *
     * <code>.NormalResponse normal_response = 5;</code>
     */
    @Override
    public NormalResponseProto.NormalResponseOrBuilder getNormalResponseOrBuilder() {
      if (onlyFiledCase_ == 5) {
         return (NormalResponseProto.NormalResponse) onlyFiled_;
      }
      return NormalResponseProto.NormalResponse.getDefaultInstance();
    }

    public static final int SESSION_ID_FIELD_NUMBER = 6;
    private volatile Object sessionId_;
    /**
     * <pre>
     *会话id
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The sessionId.
     */
    @Override
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *会话id
     * </pre>
     *
     * <code>string session_id = 6;</code>
     * @return The bytes for sessionId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JWT_FIELD_NUMBER = 7;
    private volatile Object jwt_;
    /**
     * <pre>
     *jwt
     * </pre>
     *
     * <code>string jwt = 7;</code>
     * @return The jwt.
     */
    @Override
    public String getJwt() {
      Object ref = jwt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jwt_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *jwt
     * </pre>
     *
     * <code>string jwt = 7;</code>
     * @return The bytes for jwt.
     */
    @Override
    public com.google.protobuf.ByteString
        getJwtBytes() {
      Object ref = jwt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jwt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mId_ != 0L) {
        output.writeInt64(1, mId_);
      }
      if (type_ != MessageType.PLAIN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (onlyFiledCase_ == 3) {
        output.writeMessage(3, (AuthResponseProto.AuthResponse) onlyFiled_);
      }
      if (onlyFiledCase_ == 4) {
        output.writeMessage(4, (PlainMessageProto.PlainMessage) onlyFiled_);
      }
      if (onlyFiledCase_ == 5) {
        output.writeMessage(5, (NormalResponseProto.NormalResponse) onlyFiled_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sessionId_);
      }
      if (!getJwtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, jwt_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, mId_);
      }
      if (type_ != MessageType.PLAIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (onlyFiledCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (AuthResponseProto.AuthResponse) onlyFiled_);
      }
      if (onlyFiledCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (PlainMessageProto.PlainMessage) onlyFiled_);
      }
      if (onlyFiledCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (NormalResponseProto.NormalResponse) onlyFiled_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sessionId_);
      }
      if (!getJwtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, jwt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (getMId()
          != other.getMId()) return false;
      if (type_ != other.type_) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (!getJwt()
          .equals(other.getJwt())) return false;
      if (!getOnlyFiledCase().equals(other.getOnlyFiledCase())) return false;
      switch (onlyFiledCase_) {
        case 3:
          if (!getAuthRsp()
              .equals(other.getAuthRsp())) return false;
          break;
        case 4:
          if (!getPlainMessage()
              .equals(other.getPlainMessage())) return false;
          break;
        case 5:
          if (!getNormalResponse()
              .equals(other.getNormalResponse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + M_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + JWT_FIELD_NUMBER;
      hash = (53 * hash) + getJwt().hashCode();
      switch (onlyFiledCase_) {
        case 3:
          hash = (37 * hash) + AUTH_RSP_FIELD_NUMBER;
          hash = (53 * hash) + getAuthRsp().hashCode();
          break;
        case 4:
          hash = (37 * hash) + PLAIN_MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getPlainMessage().hashCode();
          break;
        case 5:
          hash = (37 * hash) + NORMAL_RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getNormalResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mId_ = 0L;

        type_ = 0;

        sessionId_ = "";

        jwt_ = "";

        onlyFiledCase_ = 0;
        onlyFiled_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.mId_ = mId_;
        result.type_ = type_;
        if (onlyFiledCase_ == 3) {
          if (authRspBuilder_ == null) {
            result.onlyFiled_ = onlyFiled_;
          } else {
            result.onlyFiled_ = authRspBuilder_.build();
          }
        }
        if (onlyFiledCase_ == 4) {
          if (plainMessageBuilder_ == null) {
            result.onlyFiled_ = onlyFiled_;
          } else {
            result.onlyFiled_ = plainMessageBuilder_.build();
          }
        }
        if (onlyFiledCase_ == 5) {
          if (normalResponseBuilder_ == null) {
            result.onlyFiled_ = onlyFiled_;
          } else {
            result.onlyFiled_ = normalResponseBuilder_.build();
          }
        }
        result.sessionId_ = sessionId_;
        result.jwt_ = jwt_;
        result.onlyFiledCase_ = onlyFiledCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.getMId() != 0L) {
          setMId(other.getMId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (!other.getJwt().isEmpty()) {
          jwt_ = other.jwt_;
          onChanged();
        }
        switch (other.getOnlyFiledCase()) {
          case AUTH_RSP: {
            mergeAuthRsp(other.getAuthRsp());
            break;
          }
          case PLAIN_MESSAGE: {
            mergePlainMessage(other.getPlainMessage());
            break;
          }
          case NORMAL_RESPONSE: {
            mergeNormalResponse(other.getNormalResponse());
            break;
          }
          case ONLYFILED_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int onlyFiledCase_ = 0;
      private Object onlyFiled_;
      public OnlyFiledCase
          getOnlyFiledCase() {
        return OnlyFiledCase.forNumber(
            onlyFiledCase_);
      }

      public Builder clearOnlyFiled() {
        onlyFiledCase_ = 0;
        onlyFiled_ = null;
        onChanged();
        return this;
      }


      private long mId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 m_id = 1;</code>
       * @return The mId.
       */
      @Override
      public long getMId() {
        return mId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 m_id = 1;</code>
       * @param value The mId to set.
       * @return This builder for chaining.
       */
      public Builder setMId(long value) {
        
        mId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int64 m_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMId() {
        
        mId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *消息类
       * </pre>
       *
       * <code>.Message.MessageType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类
       * </pre>
       *
       * <code>.Message.MessageType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类
       * </pre>
       *
       * <code>.Message.MessageType type = 2;</code>
       * @return The type.
       */
      @Override
      public MessageType getType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(type_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类
       * </pre>
       *
       * <code>.Message.MessageType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类
       * </pre>
       *
       * <code>.Message.MessageType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          AuthResponseProto.AuthResponse, AuthResponseProto.AuthResponse.Builder, AuthResponseProto.AuthResponseOrBuilder> authRspBuilder_;
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       * @return Whether the authRsp field is set.
       */
      @Override
      public boolean hasAuthRsp() {
        return onlyFiledCase_ == 3;
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       * @return The authRsp.
       */
      @Override
      public AuthResponseProto.AuthResponse getAuthRsp() {
        if (authRspBuilder_ == null) {
          if (onlyFiledCase_ == 3) {
            return (AuthResponseProto.AuthResponse) onlyFiled_;
          }
          return AuthResponseProto.AuthResponse.getDefaultInstance();
        } else {
          if (onlyFiledCase_ == 3) {
            return authRspBuilder_.getMessage();
          }
          return AuthResponseProto.AuthResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      public Builder setAuthRsp(AuthResponseProto.AuthResponse value) {
        if (authRspBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          onlyFiled_ = value;
          onChanged();
        } else {
          authRspBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      public Builder setAuthRsp(
          AuthResponseProto.AuthResponse.Builder builderForValue) {
        if (authRspBuilder_ == null) {
          onlyFiled_ = builderForValue.build();
          onChanged();
        } else {
          authRspBuilder_.setMessage(builderForValue.build());
        }
        onlyFiledCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      public Builder mergeAuthRsp(AuthResponseProto.AuthResponse value) {
        if (authRspBuilder_ == null) {
          if (onlyFiledCase_ == 3 &&
              onlyFiled_ != AuthResponseProto.AuthResponse.getDefaultInstance()) {
            onlyFiled_ = AuthResponseProto.AuthResponse.newBuilder((AuthResponseProto.AuthResponse) onlyFiled_)
                .mergeFrom(value).buildPartial();
          } else {
            onlyFiled_ = value;
          }
          onChanged();
        } else {
          if (onlyFiledCase_ == 3) {
            authRspBuilder_.mergeFrom(value);
          }
          authRspBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      public Builder clearAuthRsp() {
        if (authRspBuilder_ == null) {
          if (onlyFiledCase_ == 3) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
            onChanged();
          }
        } else {
          if (onlyFiledCase_ == 3) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
          }
          authRspBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      public AuthResponseProto.AuthResponse.Builder getAuthRspBuilder() {
        return getAuthRspFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      @Override
      public AuthResponseProto.AuthResponseOrBuilder getAuthRspOrBuilder() {
        if ((onlyFiledCase_ == 3) && (authRspBuilder_ != null)) {
          return authRspBuilder_.getMessageOrBuilder();
        } else {
          if (onlyFiledCase_ == 3) {
            return (AuthResponseProto.AuthResponse) onlyFiled_;
          }
          return AuthResponseProto.AuthResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *认证响应
       * </pre>
       *
       * <code>.AuthResponse auth_rsp = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AuthResponseProto.AuthResponse, AuthResponseProto.AuthResponse.Builder, AuthResponseProto.AuthResponseOrBuilder> 
          getAuthRspFieldBuilder() {
        if (authRspBuilder_ == null) {
          if (!(onlyFiledCase_ == 3)) {
            onlyFiled_ = AuthResponseProto.AuthResponse.getDefaultInstance();
          }
          authRspBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AuthResponseProto.AuthResponse, AuthResponseProto.AuthResponse.Builder, AuthResponseProto.AuthResponseOrBuilder>(
                  (AuthResponseProto.AuthResponse) onlyFiled_,
                  getParentForChildren(),
                  isClean());
          onlyFiled_ = null;
        }
        onlyFiledCase_ = 3;
        onChanged();;
        return authRspBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          PlainMessageProto.PlainMessage, PlainMessageProto.PlainMessage.Builder, PlainMessageProto.PlainMessageOrBuilder> plainMessageBuilder_;
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       * @return Whether the plainMessage field is set.
       */
      @Override
      public boolean hasPlainMessage() {
        return onlyFiledCase_ == 4;
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       * @return The plainMessage.
       */
      @Override
      public PlainMessageProto.PlainMessage getPlainMessage() {
        if (plainMessageBuilder_ == null) {
          if (onlyFiledCase_ == 4) {
            return (PlainMessageProto.PlainMessage) onlyFiled_;
          }
          return PlainMessageProto.PlainMessage.getDefaultInstance();
        } else {
          if (onlyFiledCase_ == 4) {
            return plainMessageBuilder_.getMessage();
          }
          return PlainMessageProto.PlainMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      public Builder setPlainMessage(PlainMessageProto.PlainMessage value) {
        if (plainMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          onlyFiled_ = value;
          onChanged();
        } else {
          plainMessageBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 4;
        return this;
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      public Builder setPlainMessage(
          PlainMessageProto.PlainMessage.Builder builderForValue) {
        if (plainMessageBuilder_ == null) {
          onlyFiled_ = builderForValue.build();
          onChanged();
        } else {
          plainMessageBuilder_.setMessage(builderForValue.build());
        }
        onlyFiledCase_ = 4;
        return this;
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      public Builder mergePlainMessage(PlainMessageProto.PlainMessage value) {
        if (plainMessageBuilder_ == null) {
          if (onlyFiledCase_ == 4 &&
              onlyFiled_ != PlainMessageProto.PlainMessage.getDefaultInstance()) {
            onlyFiled_ = PlainMessageProto.PlainMessage.newBuilder((PlainMessageProto.PlainMessage) onlyFiled_)
                .mergeFrom(value).buildPartial();
          } else {
            onlyFiled_ = value;
          }
          onChanged();
        } else {
          if (onlyFiledCase_ == 4) {
            plainMessageBuilder_.mergeFrom(value);
          }
          plainMessageBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 4;
        return this;
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      public Builder clearPlainMessage() {
        if (plainMessageBuilder_ == null) {
          if (onlyFiledCase_ == 4) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
            onChanged();
          }
        } else {
          if (onlyFiledCase_ == 4) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
          }
          plainMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      public PlainMessageProto.PlainMessage.Builder getPlainMessageBuilder() {
        return getPlainMessageFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      @Override
      public PlainMessageProto.PlainMessageOrBuilder getPlainMessageOrBuilder() {
        if ((onlyFiledCase_ == 4) && (plainMessageBuilder_ != null)) {
          return plainMessageBuilder_.getMessageOrBuilder();
        } else {
          if (onlyFiledCase_ == 4) {
            return (PlainMessageProto.PlainMessage) onlyFiled_;
          }
          return PlainMessageProto.PlainMessage.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *普通消息
       * </pre>
       *
       * <code>.PlainMessage plain_message = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PlainMessageProto.PlainMessage, PlainMessageProto.PlainMessage.Builder, PlainMessageProto.PlainMessageOrBuilder> 
          getPlainMessageFieldBuilder() {
        if (plainMessageBuilder_ == null) {
          if (!(onlyFiledCase_ == 4)) {
            onlyFiled_ = PlainMessageProto.PlainMessage.getDefaultInstance();
          }
          plainMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PlainMessageProto.PlainMessage, PlainMessageProto.PlainMessage.Builder, PlainMessageProto.PlainMessageOrBuilder>(
                  (PlainMessageProto.PlainMessage) onlyFiled_,
                  getParentForChildren(),
                  isClean());
          onlyFiled_ = null;
        }
        onlyFiledCase_ = 4;
        onChanged();;
        return plainMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          NormalResponseProto.NormalResponse, NormalResponseProto.NormalResponse.Builder, NormalResponseProto.NormalResponseOrBuilder> normalResponseBuilder_;
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       * @return Whether the normalResponse field is set.
       */
      @Override
      public boolean hasNormalResponse() {
        return onlyFiledCase_ == 5;
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       * @return The normalResponse.
       */
      @Override
      public NormalResponseProto.NormalResponse getNormalResponse() {
        if (normalResponseBuilder_ == null) {
          if (onlyFiledCase_ == 5) {
            return (NormalResponseProto.NormalResponse) onlyFiled_;
          }
          return NormalResponseProto.NormalResponse.getDefaultInstance();
        } else {
          if (onlyFiledCase_ == 5) {
            return normalResponseBuilder_.getMessage();
          }
          return NormalResponseProto.NormalResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      public Builder setNormalResponse(NormalResponseProto.NormalResponse value) {
        if (normalResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          onlyFiled_ = value;
          onChanged();
        } else {
          normalResponseBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 5;
        return this;
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      public Builder setNormalResponse(
          NormalResponseProto.NormalResponse.Builder builderForValue) {
        if (normalResponseBuilder_ == null) {
          onlyFiled_ = builderForValue.build();
          onChanged();
        } else {
          normalResponseBuilder_.setMessage(builderForValue.build());
        }
        onlyFiledCase_ = 5;
        return this;
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      public Builder mergeNormalResponse(NormalResponseProto.NormalResponse value) {
        if (normalResponseBuilder_ == null) {
          if (onlyFiledCase_ == 5 &&
              onlyFiled_ != NormalResponseProto.NormalResponse.getDefaultInstance()) {
            onlyFiled_ = NormalResponseProto.NormalResponse.newBuilder((NormalResponseProto.NormalResponse) onlyFiled_)
                .mergeFrom(value).buildPartial();
          } else {
            onlyFiled_ = value;
          }
          onChanged();
        } else {
          if (onlyFiledCase_ == 5) {
            normalResponseBuilder_.mergeFrom(value);
          }
          normalResponseBuilder_.setMessage(value);
        }
        onlyFiledCase_ = 5;
        return this;
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      public Builder clearNormalResponse() {
        if (normalResponseBuilder_ == null) {
          if (onlyFiledCase_ == 5) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
            onChanged();
          }
        } else {
          if (onlyFiledCase_ == 5) {
            onlyFiledCase_ = 0;
            onlyFiled_ = null;
          }
          normalResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      public NormalResponseProto.NormalResponse.Builder getNormalResponseBuilder() {
        return getNormalResponseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      @Override
      public NormalResponseProto.NormalResponseOrBuilder getNormalResponseOrBuilder() {
        if ((onlyFiledCase_ == 5) && (normalResponseBuilder_ != null)) {
          return normalResponseBuilder_.getMessageOrBuilder();
        } else {
          if (onlyFiledCase_ == 5) {
            return (NormalResponseProto.NormalResponse) onlyFiled_;
          }
          return NormalResponseProto.NormalResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *普通响应
       * </pre>
       *
       * <code>.NormalResponse normal_response = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          NormalResponseProto.NormalResponse, NormalResponseProto.NormalResponse.Builder, NormalResponseProto.NormalResponseOrBuilder> 
          getNormalResponseFieldBuilder() {
        if (normalResponseBuilder_ == null) {
          if (!(onlyFiledCase_ == 5)) {
            onlyFiled_ = NormalResponseProto.NormalResponse.getDefaultInstance();
          }
          normalResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              NormalResponseProto.NormalResponse, NormalResponseProto.NormalResponse.Builder, NormalResponseProto.NormalResponseOrBuilder>(
                  (NormalResponseProto.NormalResponse) onlyFiled_,
                  getParentForChildren(),
                  isClean());
          onlyFiled_ = null;
        }
        onlyFiledCase_ = 5;
        onChanged();;
        return normalResponseBuilder_;
      }

      private Object sessionId_ = "";
      /**
       * <pre>
       *会话id
       * </pre>
       *
       * <code>string session_id = 6;</code>
       * @return The sessionId.
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *会话id
       * </pre>
       *
       * <code>string session_id = 6;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话id
       * </pre>
       *
       * <code>string session_id = 6;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话id
       * </pre>
       *
       * <code>string session_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话id
       * </pre>
       *
       * <code>string session_id = 6;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private Object jwt_ = "";
      /**
       * <pre>
       *jwt
       * </pre>
       *
       * <code>string jwt = 7;</code>
       * @return The jwt.
       */
      public String getJwt() {
        Object ref = jwt_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jwt_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *jwt
       * </pre>
       *
       * <code>string jwt = 7;</code>
       * @return The bytes for jwt.
       */
      public com.google.protobuf.ByteString
          getJwtBytes() {
        Object ref = jwt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jwt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *jwt
       * </pre>
       *
       * <code>string jwt = 7;</code>
       * @param value The jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jwt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *jwt
       * </pre>
       *
       * <code>string jwt = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearJwt() {
        
        jwt_ = getDefaultInstance().getJwt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *jwt
       * </pre>
       *
       * <code>string jwt = 7;</code>
       * @param value The bytes for jwt to set.
       * @return This builder for chaining.
       */
      public Builder setJwtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jwt_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\032\022AuthResponse.proto\032\022Pla" +
      "inMessage.proto\032\024NormalResponse.proto\"\315\002" +
      "\n\007Message\022\014\n\004m_id\030\001 \001(\003\022\"\n\004type\030\002 \001(\0162\024." +
      "Message.MessageType\022!\n\010auth_rsp\030\003 \001(\0132\r." +
      "AuthResponseH\000\022&\n\rplain_message\030\004 \001(\0132\r." +
      "PlainMessageH\000\022*\n\017normal_response\030\005 \001(\0132" +
      "\017.NormalResponseH\000\022\022\n\nsession_id\030\006 \001(\t\022\013" +
      "\n\003jwt\030\007 \001(\t\"j\n\013MessageType\022\t\n\005PLAIN\020\000\022\014\n" +
      "\010AUTH_REQ\020\001\022\014\n\010AUTH_RSP\020\002\022\021\n\rHEARTBEAT_R" +
      "EQ\020\003\022\021\n\rHEARTBEAT_RSP\020\004\022\016\n\nNORMAL_RSP\020\005B" +
      "\014\n\nonly_filedB\016B\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AuthResponseProto.getDescriptor(),
          PlainMessageProto.getDescriptor(),
          NormalResponseProto.getDescriptor(),
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "MId", "Type", "AuthRsp", "PlainMessage", "NormalResponse", "SessionId", "Jwt", "OnlyFiled", });
    AuthResponseProto.getDescriptor();
    PlainMessageProto.getDescriptor();
    NormalResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
