package cn.hiczy.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlainMessage.proto

public final class PlainMessageProto {
  private PlainMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlainMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlainMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *int64 m_id        = 1;    //消息id
     * </pre>
     *
     * <code>.PlainMessage.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *int64 m_id        = 1;    //消息id
     * </pre>
     *
     * <code>.PlainMessage.MessageType type = 2;</code>
     * @return The type.
     */
    PlainMessage.MessageType getType();

    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    long getFromId();

    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>int64 to_id = 4;</code>
     * @return The toId.
     */
    long getToId();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 create_time = 6;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <pre>
     *文件消息
     * </pre>
     *
     * <code>bytes files = 7;</code>
     * @return The files.
     */
    com.google.protobuf.ByteString getFiles();
  }
  /**
   * Protobuf type {@code PlainMessage}
   */
  public static final class PlainMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlainMessage)
      PlainMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlainMessage.newBuilder() to construct.
    private PlainMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlainMessage() {
      type_ = 0;
      content_ = "";
      files_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlainMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlainMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              fromId_ = input.readInt64();
              break;
            }
            case 32: {

              toId_ = input.readInt64();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 48: {

              createTime_ = input.readInt64();
              break;
            }
            case 58: {

              files_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlainMessageProto.internal_static_PlainMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlainMessageProto.internal_static_PlainMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlainMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code PlainMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *文本消息
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <pre>
       *图片消息
       * </pre>
       *
       * <code>PICTURE = 1;</code>
       */
      PICTURE(1),
      /**
       * <pre>
       *文件消息
       * </pre>
       *
       * <code>FILE = 2;</code>
       */
      FILE(2),
      /**
       * <pre>
       *语音消息
       * </pre>
       *
       * <code>VOICE = 3;</code>
       */
      VOICE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *文本消息
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <pre>
       *图片消息
       * </pre>
       *
       * <code>PICTURE = 1;</code>
       */
      public static final int PICTURE_VALUE = 1;
      /**
       * <pre>
       *文件消息
       * </pre>
       *
       * <code>FILE = 2;</code>
       */
      public static final int FILE_VALUE = 2;
      /**
       * <pre>
       *语音消息
       * </pre>
       *
       * <code>VOICE = 3;</code>
       */
      public static final int VOICE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return PICTURE;
          case 2: return FILE;
          case 3: return VOICE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PlainMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PlainMessage.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *int64 m_id        = 1;    //消息id
     * </pre>
     *
     * <code>.PlainMessage.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *int64 m_id        = 1;    //消息id
     * </pre>
     *
     * <code>.PlainMessage.MessageType type = 2;</code>
     * @return The type.
     */
    @Override public MessageType getType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(type_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int FROM_ID_FIELD_NUMBER = 3;
    private long fromId_;
    /**
     * <pre>
     *发送人id
     * </pre>
     *
     * <code>int64 from_id = 3;</code>
     * @return The fromId.
     */
    @Override
    public long getFromId() {
      return fromId_;
    }

    public static final int TO_ID_FIELD_NUMBER = 4;
    private long toId_;
    /**
     * <pre>
     *接收人id
     * </pre>
     *
     * <code>int64 to_id = 4;</code>
     * @return The toId.
     */
    @Override
    public long getToId() {
      return toId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>int64 create_time = 6;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int FILES_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString files_;
    /**
     * <pre>
     *文件消息
     * </pre>
     *
     * <code>bytes files = 7;</code>
     * @return The files.
     */
    @Override
    public com.google.protobuf.ByteString getFiles() {
      return files_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != MessageType.TEXT.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (fromId_ != 0L) {
        output.writeInt64(3, fromId_);
      }
      if (toId_ != 0L) {
        output.writeInt64(4, toId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(6, createTime_);
      }
      if (!files_.isEmpty()) {
        output.writeBytes(7, files_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fromId_);
      }
      if (toId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, toId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (!files_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, files_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlainMessage)) {
        return super.equals(obj);
      }
      PlainMessage other = (PlainMessage) obj;

      if (type_ != other.type_) return false;
      if (getFromId()
          != other.getFromId()) return false;
      if (getToId()
          != other.getToId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (!getFiles()
          .equals(other.getFiles())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFiles().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlainMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlainMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlainMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlainMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlainMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlainMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlainMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlainMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlainMessage)
        PlainMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlainMessageProto.internal_static_PlainMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlainMessageProto.internal_static_PlainMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlainMessage.class, Builder.class);
      }

      // Construct using PlainMessageProto.PlainMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        fromId_ = 0L;

        toId_ = 0L;

        content_ = "";

        createTime_ = 0L;

        files_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlainMessageProto.internal_static_PlainMessage_descriptor;
      }

      @Override
      public PlainMessage getDefaultInstanceForType() {
        return PlainMessage.getDefaultInstance();
      }

      @Override
      public PlainMessage build() {
        PlainMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlainMessage buildPartial() {
        PlainMessage result = new PlainMessage(this);
        result.type_ = type_;
        result.fromId_ = fromId_;
        result.toId_ = toId_;
        result.content_ = content_;
        result.createTime_ = createTime_;
        result.files_ = files_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlainMessage) {
          return mergeFrom((PlainMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlainMessage other) {
        if (other == PlainMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getToId() != 0L) {
          setToId(other.getToId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getFiles() != com.google.protobuf.ByteString.EMPTY) {
          setFiles(other.getFiles());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlainMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlainMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *int64 m_id        = 1;    //消息id
       * </pre>
       *
       * <code>.PlainMessage.MessageType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *int64 m_id        = 1;    //消息id
       * </pre>
       *
       * <code>.PlainMessage.MessageType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int64 m_id        = 1;    //消息id
       * </pre>
       *
       * <code>.PlainMessage.MessageType type = 2;</code>
       * @return The type.
       */
      @Override
      public MessageType getType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(type_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *int64 m_id        = 1;    //消息id
       * </pre>
       *
       * <code>.PlainMessage.MessageType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int64 m_id        = 1;    //消息id
       * </pre>
       *
       * <code>.PlainMessage.MessageType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>int64 from_id = 3;</code>
       * @return The fromId.
       */
      @Override
      public long getFromId() {
        return fromId_;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>int64 from_id = 3;</code>
       * @param value The fromId to set.
       * @return This builder for chaining.
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人id
       * </pre>
       *
       * <code>int64 from_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>int64 to_id = 4;</code>
       * @return The toId.
       */
      @Override
      public long getToId() {
        return toId_;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>int64 to_id = 4;</code>
       * @param value The toId to set.
       * @return This builder for chaining.
       */
      public Builder setToId(long value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人id
       * </pre>
       *
       * <code>int64 to_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToId() {
        
        toId_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 5;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 create_time = 6;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 create_time = 6;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>int64 create_time = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString files_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *文件消息
       * </pre>
       *
       * <code>bytes files = 7;</code>
       * @return The files.
       */
      @Override
      public com.google.protobuf.ByteString getFiles() {
        return files_;
      }
      /**
       * <pre>
       *文件消息
       * </pre>
       *
       * <code>bytes files = 7;</code>
       * @param value The files to set.
       * @return This builder for chaining.
       */
      public Builder setFiles(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        files_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件消息
       * </pre>
       *
       * <code>bytes files = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFiles() {
        
        files_ = getDefaultInstance().getFiles();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlainMessage)
    }

    // @@protoc_insertion_point(class_scope:PlainMessage)
    private static final PlainMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlainMessage();
    }

    public static PlainMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlainMessage>
        PARSER = new com.google.protobuf.AbstractParser<PlainMessage>() {
      @Override
      public PlainMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlainMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlainMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlainMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public PlainMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlainMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlainMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022PlainMessage.proto\"\307\001\n\014PlainMessage\022\'\n" +
      "\004type\030\002 \001(\0162\031.PlainMessage.MessageType\022\017" +
      "\n\007from_id\030\003 \001(\003\022\r\n\005to_id\030\004 \001(\003\022\017\n\007conten" +
      "t\030\005 \001(\t\022\023\n\013create_time\030\006 \001(\003\022\r\n\005files\030\007 " +
      "\001(\014\"9\n\013MessageType\022\010\n\004TEXT\020\000\022\013\n\007PICTURE\020" +
      "\001\022\010\n\004FILE\020\002\022\t\n\005VOICE\020\003B\023B\021PlainMessagePr" +
      "otob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlainMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlainMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlainMessage_descriptor,
        new String[] { "Type", "FromId", "ToId", "Content", "CreateTime", "Files", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
