server:
  port: 6000

spring:
  application:
    name: post-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    username: root
    password: 123456@czy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.31.223:4406/post_db
