
chat-server:
  backlog-num: 1024
  port: 9333
spring:
  datasource:
    username: root
    password: 123456@czy
    url: jdbc:mysql://121.199.31.223:6606/message_db
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名 开启逻辑删除功能
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)